Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -74,7 +74,7 @@ jobs:
           source: "docker-compose.yaml"
           target: "/home/ubuntu"
 
-  file-transfer-bash-script:
+    file-transfer-bash-script:
     runs-on: ubuntu-latest
     needs: file-transfer-dockercompose
     steps:
@@ -83,6 +83,9 @@ jobs:
 
       - name: Debug - List files before transfer
         run: ls -lah
+
+      - name: Debug - Check if docker.sh exists
+        run: test -f docker.sh && echo "docker.sh exists" || echo "docker.sh is missing!"
 
       - name: Copy bash script via SSH
         uses: appleboy/scp-action@v0.1.7
@@ -93,6 +96,7 @@ jobs:
           port: ${{ secrets.PORT }}
           source: "docker.sh"
           target: "/home/ubuntu"
+
 
   deploy:
     runs-on: ubuntu-latest
